### ISSUE TITLE
Namespace Branch: Errors and Warnings

### ISSUE THREAD

**Issue by advation** [Staple-Code/Staple-Code#17]
We will need to resolve the following errors before we can continue to develop out the front end for the public site. 

```
Warning: require_once(/projects/Staple-Public/library/Staple/Traits\Singleton.trait.php): failed to open stream: No such file or directory in /projects/Staple-Public/library/Staple/Config.class.php on line 31

Fatal error: require_once(): Failed opening required '/projects/Staple-Public/library/Staple/Traits\Singleton.trait.php' (include_path='.:/usr/share/php:/usr/share/pear') in /projects/Staple-Public/library/Staple/Config.class.php on line 31
```

**Comment by ironpilot** [comment]
I merged in the Query PDO branch with had a resolution for this issue inside of it. If this resolved the issue then you can close it out.

**Comment by advation** [comment]
Did you merge the Query PDO branch into the Namespacing branch?

**Comment by ironpilot** [comment]
Yes I did.

**Comment by advation** [comment]
K just did a fresh pull on the Namespacing branch and still getting the same errors:

```
Warning: require_once(/projects/Staple-Code/library/Staple/Traits\Singleton.trait.php): failed to open stream: No such file or directory in /projects/Staple-Code/library/Staple/Config.class.php on line 31

Fatal error: require_once(): Failed opening required '/projects/Staple-Code/library/Staple/Traits\Singleton.trait.php' (include_path='.:/usr/share/php:/usr/share/pear') in /projects/Staple-Code/library/Staple/Config.class.php on line 31
```

**Comment by ironpilot** [comment]
Same issue huh? Well I'll have to investigate.
